#!/bin/zsh

#g++ "$1" -o prog -std=c++17 -I/opt/homebrew/Cellar/sfml/2.5.1_1/include/ -I/opt/homebrew/Cellar/eigen/3.4.0_1/include/eigen3/ -L/opt/homebrew/Cellar/sfml/2.5.1_1/lib -lsfml-window -lsfml-system -lsfml-audio -lsfml-graphics



#g++ "$1" -o prog -std=c++17 -I/opt/homebrew/Cellar/eigen/3.4.0_1/include/eigen3/ -I/../include -I/../include/ -framework Cocoa -framework OpenGL -framework IOKit -lglfw3 


g++ "$1" glad.c -o output -std=c++17 -I../include/ -I/opt/homebrew/Cellar/eigen/3.4.0_1/include/eigen3/ -framework Cocoa -framework OpenGL -framework IOKit -lglfw3 


